### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jchodera** [choderalab/AurA-materials#4]
Following the guidance of [this Victoria Stodden paper](https://web.stanford.edu/~vcs/papers/LFRSR12012008.pdf), we should add licenses for the coda and data made available in this repo:
* All code should be made available under the permissive OSI-approved [MIT License](https://opensource.org/licenses/MIT)
* All data should be made available under the [CC BY 4.0 License](https://creativecommons.org/licenses/by/4.0/) - [legal code](https://creativecommons.org/licenses/by/4.0/legalcode)

@steven-albanese : Could you add the formatted text versions of this to the repo and update the `README.md` to reflect these licenses?

**Comment by steven-albanese** [comment]
@jchodera I've added the `MIT` license, but I'm not sure how to handle the license for the data. We also haven't yet made the data for the eLife paper available yet

**Comment by jchodera** [comment]
We need a data license in the repo for people to use the processed data that we provide in this repo. (And we should try to include the processed data here that we have been plotting if it's small enough---under 1 GB, say.) 

I'd add the following text to README:
```
* The software in this repository is made available under the [MIT License](https://opensource.org/licenses/MIT) - a copy of this license is provided as `SOFTWARE_LICENSE`
* The data in this repository is made available under the [CC BY 4.0 License](https://creativecommons.org/licenses/by/4.0/) - a copy of this license is provided as `DATA_LICENSE`
```
You can grab a plaintext copy of the `DATA_LICENSE` [here](https://creativecommons.org/licenses/by/4.0/legalcode.txt).

**Comment by jchodera** [comment]
We should also start uploading the nosolvent FAH data we used to OSF. Is there a README somewhere with all the FAH project numbers in it that I can compile and start uploading?

**Comment by steven-albanese** [comment]
The processed data for the phosphorylation paper is uploaded [here](https://github.com/choderalab/AurA-materials/tree/master/phosphorylation-paper/AMBER-wt-analysis/data) for the AMBER data and [here](https://github.com/choderalab/AurA-materials/tree/master/phosphorylation-paper/spin-probe-analysis) for the spin probe CHARMM data. 

I can add the CHARMM WT data if you think we should. I haven't so far because it isn't used in the paper

**Comment by jchodera** [comment]
> The processed data for the phosphorylation paper is uploaded here for the AMBER data and here for the spin probe CHARMM data.

Great---that's already taken care of then.

> I can add the CHARMM WT data if you think we should. I haven't so far because it isn't used in the paper

We don't need to add it if it's not in the paper.

I'll start uploading the trajectory data to OSF once you compile project numbers, but I think we're good to go once these PRs are merged.

**Comment by steven-albanese** [comment]
Ok! I'm just compiling the README now. I'll add it to the `phosphorylation-paper` directory in a moment

**Comment by steven-albanese** [comment]
I've added the project list here: https://github.com/choderalab/AurA-materials/tree/master/phosphorylation-paper

I've only included the projects and `RUNS` that were used in the paper (i.e., I've filtered out all of the mutant RUNS so we didn't look at those).

**Comment by jchodera** [comment]
Thanks! I'll stage and upload those!

**Comment by steven-albanese** [comment]
I think this has been resolved, so I'll close this now. I am going to open a separate issue for the OSF upload
